inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - kanayago.gemspec

Metrics/AbcSize:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

RBS:
  Enabled: true

Style/Documentation:
  Enabled: false

require:
  - rubocop-minitest
  - rubocop-on-rbs
  - rubocop-rake

