inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - kanayago.gemspec

Metrics/AbcSize:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

RBS:
  Enabled: true

Style/Documentation:
  Enabled: false

Minitest/UselessAssertion:
  Exclude:
    - test/kanayago/global_assignment_node_test.rb
    - test/kanayago/parse_args_cat_test.rb 
    - test/kanayago/parse_args_push_test.rb
    - test/kanayago/parse_attrasgn_test.rb 

plugins:
  - rubocop-minitest
  - rubocop-on-rbs
  - rubocop-rake

