# Offense count: 4
# Configuration parameters: CountComments, CountAsOne.
Metrics/ClassLength:
  Max: 318

# Offense count: 40
# Configuration parameters: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 49

# Offense count: 2
# Configuration parameters: AllowedConstants.
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Offense count: 4
# Configuration parameters: AllowedVariables.
Style/GlobalVars:
  Exclude:
    - 'ext/kanayago/extconf.rb'

